ALTER TABLE banners ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(), ADD COLUMN IF NOT EXISTS end_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '1 year';
ALTER TABLE banners ADD COLUMN IF NOT EXISTS always_show BOOLEAN DEFAULT FALSE;
